/**
 * Codex OAuth image-generation fallback client.
 */

import { EnvConfig, GeneratedImage, AspectRatio, ImageSize } from '../types';
import { Logger } from '../utils/logger';
import { requestUrl } from 'obsidian';
import * as fs from 'fs';
import * as path from 'path';

interface CodexAuthFile {
	access_token?: string;
	account_id?: string;
}

interface CodexAuth {
	accessToken: string;
	accountId?: string;
}

interface CodexImageGenerationItem {
	type?: string;
	result?: string;
}

interface CodexSsePayload {
	item?: CodexImageGenerationItem;
}

const CODEX_RESPONSES_URL = 'https://chatgpt.com/backend-api/codex/responses';
const CODEX_RESPONSES_MODEL = 'gpt-5.5';
const CODEX_IMAGE_MODEL = 'gpt-image-2';
const CODEX_IMAGE_SIZE = '2048x1152';
const CODEX_IMAGE_QUALITY = 'low';
const CODEX_IMAGE_FORMAT = 'png';

function resolveHomePath(filePath: string): string {
	return filePath.startsWith('~')
		? path.join(process.env.HOME || '', filePath.slice(1))
		: filePath;
}

function readCodexAuthFile(filePath: string): CodexAuth | null {
	const resolvedPath = resolveHomePath(filePath);
	if (!fs.existsSync(resolvedPath)) return null;

	const raw = fs.readFileSync(resolvedPath, 'utf-8');
	const parsed = JSON.parse(raw) as CodexAuthFile;
	if (!parsed.access_token) return null;

	return {
		accessToken: parsed.access_token,
		accountId: parsed.account_id,
	};
}

function resolveCodexAuth(config: EnvConfig): CodexAuth | null {
	if (config.codexAccessToken) {
		return {
			accessToken: config.codexAccessToken,
			accountId: config.codexAccountId,
		};
	}

	return readCodexAuthFile(config.codexAuthFilePath ?? '~/.codex/auth.json');
}

function parseCodexImageResult(sseText: string): string {
	for (const line of sseText.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed.startsWith('data:')) continue;

		const raw = trimmed.slice('data:'.length).trim();
		if (!raw || raw === '[DONE]') continue;

		let payload: CodexSsePayload;
		try {
			payload = JSON.parse(raw) as CodexSsePayload;
		} catch {
			continue;
		}

		if (payload.item?.type === 'image_generation_call' && payload.item.result) {
			return payload.item.result;
		}
	}

	throw new Error('No image was generated by Codex OAuth fallback.');
}

export class CodexOAuthImageClient {
	constructor(
		private config: EnvConfig,
		private logger: Logger,
		private timeoutMs: number
	) {}

	async generateImage(
		systemPrompt: string,
		userText: string,
		aspectRatio: AspectRatio,
		imageSize: ImageSize
	): Promise<GeneratedImage> {
		const auth = resolveCodexAuth(this.config);
		if (!auth) {
			throw new Error('Codex OAuth auth is not configured. Run codex login or set CODEX_ACCESS_TOKEN.');
		}

		this.logger.debug('Codex OAuth fallback uses fixed image settings; prompt image settings are ignored', {
			aspectRatio,
			imageSize,
			size: CODEX_IMAGE_SIZE,
			quality: CODEX_IMAGE_QUALITY,
			format: CODEX_IMAGE_FORMAT,
		});

		const headers: Record<string, string> = {
			'Content-Type': 'application/json',
			'Authorization': `Bearer ${auth.accessToken}`,
		};
		if (auth.accountId) {
			headers['ChatGPT-Account-ID'] = auth.accountId;
		}

		const body = {
			model: CODEX_RESPONSES_MODEL,
			input: `${systemPrompt}\n\n---\n\n${userText}`,
			tools: [{
				type: 'image_generation',
				model: CODEX_IMAGE_MODEL,
				size: CODEX_IMAGE_SIZE,
				quality: CODEX_IMAGE_QUALITY,
				output_format: CODEX_IMAGE_FORMAT,
			}],
		};

		const timeoutPromise = new Promise<never>((_, reject) =>
			setTimeout(
				() => reject(new Error(`Request timed out after ${this.timeoutMs / 1000} seconds`)),
				this.timeoutMs
			)
		);

		const response = await Promise.race([
			requestUrl({
				url: CODEX_RESPONSES_URL,
				method: 'POST',
				headers,
				body: JSON.stringify(body),
				throw: false,
			}),
			timeoutPromise,
		]);

		if (response.status >= 400) {
			this.logger.error('Codex OAuth API HTTP error', {
				status: response.status,
				bodyLength: response.text?.length ?? 0,
			});
			throw new Error(`Codex OAuth API error: HTTP ${response.status}`);
		}

		return { data: parseCodexImageResult(response.text ?? ''), mimeType: 'image/png' };
	}
}
