/**
 * Codex OAuth image-generation fallback client.
 */

import { EnvConfig, GeneratedImage, AspectRatio, ImageSize } from '../types';
import { Logger } from '../utils/logger';
import { requestUrl } from 'obsidian';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

interface CodexAuthFile {
	access_token?: string;
	account_id?: string;
	chatgpt_account_id?: string;
	tokens?: {
		access_token?: string;
		account_id?: string;
	};
	account?: {
		id?: string;
	};
}

interface CodexAuth {
	accessToken: string;
	accountId?: string;
}

interface CodexImageGenerationItem {
	type?: string;
	result?: string;
}

interface CodexSsePayload {
	type?: string;
	error?: { message?: string };
	item?: CodexImageGenerationItem;
	response?: {
		output?: CodexImageGenerationItem[];
	};
}

const CODEX_RESPONSES_URL = 'https://chatgpt.com/backend-api/codex/responses';
const CODEX_RESPONSES_MODEL = 'gpt-5.5';
const CODEX_IMAGE_MODEL = 'gpt-image-2';
const CODEX_IMAGE_SIZE = '2048x1152';
const CODEX_IMAGE_QUALITY = 'low';
const CODEX_IMAGE_FORMAT = 'png';

function resolveHomePath(filePath: string): string {
	return filePath.startsWith('~')
		? path.join(os.homedir() || process.env.USERPROFILE || process.env.HOME || '', filePath.slice(1))
		: filePath;
}

function readCodexAuthFile(filePath: string): CodexAuth | null {
	const resolvedPath = resolveHomePath(filePath);
	if (!fs.existsSync(resolvedPath)) return null;

	const raw = fs.readFileSync(resolvedPath, 'utf-8');
	const parsed = JSON.parse(raw) as CodexAuthFile;
	const accessToken = parsed.tokens?.access_token ?? parsed.access_token;
	if (!accessToken) return null;

	return {
		accessToken,
		accountId: parsed.tokens?.account_id ?? parsed.account_id ?? parsed.chatgpt_account_id ?? parsed.account?.id,
	};
}

function resolveCodexAuth(config: EnvConfig): CodexAuth | null {
	if (config.codexAccessToken) {
		return {
			accessToken: config.codexAccessToken,
			accountId: config.codexAccountId,
		};
	}

	if (!config.codexAuthFilePath && !config.codexFallbackEnabled) {
		throw new Error('Codex OAuth fallback is not enabled. Set CODEX_FALLBACK_ENABLED=true, CODEX_AUTH_FILE_PATH, or CODEX_ACCESS_TOKEN.');
	}

	return readCodexAuthFile(config.codexAuthFilePath ?? '~/.codex/auth.json');
}

function validatePngBase64(b64: string): void {
	let bytes: Buffer;
	try {
		bytes = Buffer.from(b64, 'base64');
	} catch (error) {
		throw new Error(`Generated image is not valid base64: ${error instanceof Error ? error.message : String(error)}`);
	}

	if (bytes.length < 8 || !bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
		throw new Error('Generated image is not a PNG');
	}
}

function parseCodexImageResult(sseText: string): string {
	for (const line of sseText.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed.startsWith('data:')) continue;

		const raw = trimmed.slice('data:'.length).trim();
		if (!raw || raw === '[DONE]') continue;

		let payload: CodexSsePayload;
		try {
			payload = JSON.parse(raw) as CodexSsePayload;
		} catch {
			continue;
		}

		if (payload.type === 'response.failed' || payload.type === 'response.incomplete' || payload.type === 'error') {
			throw new Error(`Codex image generation failed: ${payload.error?.message ?? raw}`);
		}

		if (payload.item?.type === 'image_generation_call' && payload.item.result) {
			return payload.item.result;
		}

		const output = payload.response?.output;
		if (Array.isArray(output)) {
			for (const item of output) {
				if (item.type === 'image_generation_call' && item.result) {
					return item.result;
				}
			}
		}
	}

	throw new Error('No image was generated by Codex OAuth fallback.');
}

export class CodexOAuthImageClient {
	constructor(
		private config: EnvConfig,
		private logger: Logger,
		private timeoutMs: number
	) {}

	async generateImage(
		systemPrompt: string,
		userText: string,
		aspectRatio: AspectRatio,
		imageSize: ImageSize
	): Promise<GeneratedImage> {
		const auth = resolveCodexAuth(this.config);
		if (!auth) {
			throw new Error('Codex OAuth auth is not configured. Run codex login or set CODEX_ACCESS_TOKEN.');
		}

		this.logger.debug('Codex OAuth fallback uses fixed image settings; prompt image settings are ignored', {
			aspectRatio,
			imageSize,
			size: CODEX_IMAGE_SIZE,
			quality: CODEX_IMAGE_QUALITY,
			format: CODEX_IMAGE_FORMAT,
		});

		const headers: Record<string, string> = {
			'Content-Type': 'application/json',
			'Accept': 'text/event-stream',
			'Authorization': `Bearer ${auth.accessToken}`,
		};
		if (auth.accountId) {
			headers['ChatGPT-Account-ID'] = auth.accountId;
		}

		const body = {
			model: CODEX_RESPONSES_MODEL,
			instructions: systemPrompt,
			input: [{
				role: 'user',
				content: [{ type: 'input_text', text: userText }],
			}],
			tools: [{
				type: 'image_generation',
				model: CODEX_IMAGE_MODEL,
				size: CODEX_IMAGE_SIZE,
				quality: CODEX_IMAGE_QUALITY,
			}],
			tool_choice: { type: 'image_generation' },
			stream: true,
			store: false,
		};

		const timeoutPromise = new Promise<never>((_, reject) =>
			setTimeout(
				() => reject(new Error(`Request timed out after ${this.timeoutMs / 1000} seconds`)),
				this.timeoutMs
			)
		);

		const response = await Promise.race([
			requestUrl({
				url: CODEX_RESPONSES_URL,
				method: 'POST',
				headers,
				body: JSON.stringify(body),
				throw: false,
			}),
			timeoutPromise,
		]);

		if (response.status >= 400) {
			this.logger.error('Codex OAuth API HTTP error', {
				status: response.status,
				bodyLength: response.text?.length ?? 0,
			});
			throw new Error(`Codex OAuth API error: HTTP ${response.status}`);
		}

		const data = parseCodexImageResult(response.text ?? '');
		validatePngBase64(data);
		return { data, mimeType: 'image/png' };
	}
}
