/**
 * OpenAI Images API client used as a fallback when Gemini generation fails.
 */

import { requestUrl } from 'obsidian';
import { EnvConfig, GeneratedImage, AspectRatio, ImageSize } from '../types';
import { Logger } from '../utils/logger';

interface OpenAIImagesResponse {
	data?: { b64_json?: string }[];
	error?: { message?: string; code?: string | number };
}

type OpenAISize = string;

const ASPECT_RATIO_TO_OPENAI_SIZE: Partial<Record<AspectRatio, OpenAISize>> = {
	'1:1': '1024x1024',
	'16:9': '1536x864',
	'4:3': '1408x1056',
	'3:2': '1536x1024',
	'5:4': '1280x1024',
	'21:9': '2016x864',
	'9:16': '864x1536',
	'2:3': '1024x1536',
	'3:4': '1056x1408',
	'4:5': '1024x1280',
};

function mapAspectRatioToSize(aspectRatio: AspectRatio, logger: Logger): OpenAISize {
	const mapped = ASPECT_RATIO_TO_OPENAI_SIZE[aspectRatio];
	if (mapped) return mapped;
	logger.warn('Unsupported aspect ratio for OpenAI, defaulting to 1024x1024', { aspectRatio });
	return '1024x1024';
}

export class OpenAIClient {
	private config: EnvConfig;
	private logger: Logger;
	private timeoutMs: number;

	constructor(config: EnvConfig, logger: Logger, timeoutMs: number) {
		this.config = config;
		this.logger = logger;
		this.timeoutMs = timeoutMs;
	}

	async generateImage(
		systemPrompt: string,
		userText: string,
		aspectRatio: AspectRatio,
		imageSize: ImageSize
	): Promise<GeneratedImage> {
		const baseUrl = (this.config.openaiBaseUrl ?? 'https://api.openai.com/v1').replace(/\/+$/, '');
		const url = `${baseUrl}/images/generations`;
		const apiKey = this.config.openaiApiKey ?? '';
		const model = this.config.openaiModel ?? 'gpt-image-2';
		if (model !== 'gpt-image-2') {
			throw new Error('Only gpt-image-2 is supported by the OpenAI fallback. Set OPENAI_MODEL to gpt-image-2 or omit it.');
		}

		const size = mapAspectRatioToSize(aspectRatio, this.logger);
		this.logger.debug('OpenAI ignores imageSize parameter (no equivalent in gpt-image API)', { imageSize });

		const prompt = `${systemPrompt}\n\n---\n\n${userText}`;
		const body = {
			model,
			prompt,
			size,
			n: 1,
		};

		const timeoutPromise = new Promise<never>((_, reject) =>
			setTimeout(
				() => reject(new Error(`Request timed out after ${this.timeoutMs / 1000} seconds`)),
				this.timeoutMs
			)
		);

		const response = await Promise.race([
			requestUrl({
				url,
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Authorization': `Bearer ${apiKey}`,
				},
				body: JSON.stringify(body),
				throw: false,
			}),
			timeoutPromise,
		]);

		if (response.status >= 400) {
			this.logger.error('OpenAI API HTTP error', {
				status: response.status,
				bodyLength: response.text?.length ?? 0,
			});
			throw new Error(`OpenAI API error: HTTP ${response.status}`);
		}

		const json = response.json as OpenAIImagesResponse;
		const b64 = json.data?.[0]?.b64_json;
		if (!b64) {
			throw new Error('No image was generated by OpenAI.');
		}
		return { data: b64, mimeType: 'image/png' };
	}
}
